import { Open_Sans } from "next/font/google";
import "./globals.css";
import Navbar from "@/components/Navbar/Navbar";
import Footer from "@/components/Footer/Footer";
import Header from "@/components/Navbar/Header";

const openSans = Open_Sans({
  subsets: ["latin"],
  weight: [ "300", "400", "500", "600", "700", "800"],
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={`${openSans.className} bg-gray-50`}>
        <Header />
        {children}
        <Footer />
      </body>
    </html>
  );
}
